# -*- coding: utf-8 -*-

LANGUAGES = (
    (0, ('ru', u"Русский")),
    (1, ('uk', u"Українська")),
    (2, ('be', u"Беларуская (тарашкевiца)")),
    (3, ('en', u"English")),
    (4, ('es', u"Español")),
    (5, (None, u"Suomi")),
    (6, ('de', u"Deutsch")),
    (7, ('it', u"Italiano")),
    (8, ('bg', u"Български")),
    (9, ('hr', u"Hrvatski")),
    (10, ('sl', u"Magyar")),
    (11, ('sr', u"Српски")),
    (12, ('pt', u"Português")),
    (14, ('el', u"Ελληνική")),
    (15, ('pl', u"Polski")),
    (16, ('fr', u"Français")),
    (17, (None, u"한국어")),
    (18, (None, u"汉语")),
    (19, (None, u"Lietuvių")),
    (20, (None, u"日本語")),
    (21, (None, u"Čeština")),
    (22, (None, u"Eesti")),
    (53, ('sk', u"Slovenčina")),
    (54, (None, u"Română")),
    (55, ('no', u"Norsk")),
    (56, (None, u"Latviešu")),
    (57, (None, u"Azərbaycan")),
    (58, (None, u"Հայերեն")),
    (59, (None, u"Shqip")),
    (60, ('sv', u"Svenska")),
    (61, ('nl', u"Nederlands")),
    (62, (None, u"Türkmen")),
    (63, (None, u"ქართული")),
    (64, ('da', u"Dansk")),
    (65, (None, u"O‘zbek")),
    (66, ('mo', u"Moldovenească")),
    (68, (None, u"ภาษาไทย")),
    (69, (None, u"Bahasa Indonesia")),
    (70, (None, u"Тоҷикӣ")),
    (71, (None, u"Slovenščina")),
    (72, (None, u"Bosanski")),
    (73, (None, u"Português brasileiro")),
    (74, (None, u"پارسی")),
    (75, (None, u"Việt Nam")),
    (76, (None, u"हिन्दी")),
    (77, (None, u"සිංහල")),
    (78, (None, u"বাংলা Bāṇlā")),
    (79, (None, u"Tagalog")),
    (80, (None, u"Монгол")),
    (81, (None, u"ဗမာစာ")),
    (82, (None, u"Türkçe")),
    (83, (None, u"नेपाली")),
    (85, (None, u"اردو")),
    (86, (None, u"Bahasa Melayu")),
    (87, (None, u"Кыргыз тили")),
    (90, (None, u"پنجابی")),
    (91, (None, u"Иронау")),
    (94, (None, u"ಕನ್ನಡ")),
    (95, (None, u"Kiswahili")),
    (97, (None, u"Қазақша")),
    (98, (None, u"العربية")),
    (99, (None, u"עברית")),
    (100, (None, u"Дореволюцiонный")),
    (102, (None, u"Адыгэбзэ")),
    (777, (None, u"В Союзе")),
)
